apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beagle-web.fullname" . }}
  labels:
    {{- include "beagle-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "beagle-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "beagle-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: web
          image: {{ include "beagle-web.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
